language: java
jdk:
- oraclejdk8
before_script:
- git checkout -b release
- if [ "$TRAVIS_BRANCH" == "master"  ]; then MVN_GOAL="verify"; fi
- if [ "$TRAVIS_BRANCH" == "release" ]; then MVN_GOAL="release:prepare release:perform"; fi
script:
- mvn -B $MVN_GOAL
