language: java
jdk:
- oraclejdk8
before_script:
- GOAL=verify
- if [ "${TRAVIS_BRANCH}" = "release" && "${TRAVIS_PULL_REQUEST}" = "false" ]; then GOAL="release:prepare release:perform"; fi;
- echo ${TRAVIS_BRANCH}
- echo ${TRAVIS_PULL_REQUEST}
- echo $GOAL
script:
- mvn -B -Dusername=$GH_TOKEN clean $GOAL