language: java
jdk:
- oraclejdk8
before_script:
- git checkout -b travis
- if [ "$TRAVIS_BRANCH" == "master"  ]; then MVN_GOAL="verify"; fi
- if [ "$TRAVIS_BRANCH" == "release" ]; then MVN_GOAL="release:prepare release:perform"; fi
- if [ "$TRAVIS_TAG"                 ]; then MVN_GOAL="beanstalk:upload-source-bundle beanstalk:create-application-version beanstalk:replace-environment"; fi
script:
- mvn -B $MVN_GOAL
